services:
    ftc2.autoresize.listener:
        class: ftc2\autoresize\event\main_listener
        arguments:
            - '@config'
            - '@user'
            - '@ftc2.autoresize.core'
        tags:
            - { name: event.listener }
    ftc2.autoresize.core:
        class: ftc2\autoresize\core\core_functions
        arguments:
            - '@config'
            - '@user'
